.align   4

.globl _isr_wrapper_0
_isr_wrapper_0:
	pushal
	pushl $0
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_1
_isr_wrapper_1:
	pushal
	pushl $1
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_2
_isr_wrapper_2:
	pushal
	pushl $2
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_3
_isr_wrapper_3:
	pushal
	pushl $3
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_4
_isr_wrapper_4:
	pushal
	pushl $4
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_5
_isr_wrapper_5:
	pushal
	pushl $5
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_6
_isr_wrapper_6:
	pushal
	pushl $6
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_7
_isr_wrapper_7:
	pushal
	pushl $7
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_8
_isr_wrapper_8:
	pushal
	pushl $8
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_9
_isr_wrapper_9:
	pushal
	pushl $9
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_10
_isr_wrapper_10:
	pushal
	pushl $10
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_11
_isr_wrapper_11:
	pushal
	pushl $11
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_12
_isr_wrapper_12:
	pushal
	pushl $12
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_13
_isr_wrapper_13:
	pushal
	pushl $13
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_14
_isr_wrapper_14:
	pushal
	pushl $14
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_15
_isr_wrapper_15:
	pushal
	pushl $15
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_16
_isr_wrapper_16:
	pushal
	pushl $16
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_17
_isr_wrapper_17:
	pushal
	pushl $17
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_18
_isr_wrapper_18:
	pushal
	pushl $18
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_19
_isr_wrapper_19:
	pushal
	pushl $19
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_20
_isr_wrapper_20:
	pushal
	pushl $20
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_21
_isr_wrapper_21:
	pushal
	pushl $21
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_22
_isr_wrapper_22:
	pushal
	pushl $22
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_23
_isr_wrapper_23:
	pushal
	pushl $23
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_24
_isr_wrapper_24:
	pushal
	pushl $24
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_25
_isr_wrapper_25:
	pushal
	pushl $25
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_26
_isr_wrapper_26:
	pushal
	pushl $26
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_27
_isr_wrapper_27:
	pushal
	pushl $27
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_28
_isr_wrapper_28:
	pushal
	pushl $28
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_29
_isr_wrapper_29:
	pushal
	pushl $29
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_30
_isr_wrapper_30:
	pushal
	pushl $30
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_31
_isr_wrapper_31:
	pushal
	pushl $31
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_32
_isr_wrapper_32:
	pushal
	pushl $32
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_33
_isr_wrapper_33:
	pushal
	pushl $33
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_34
_isr_wrapper_34:
	pushal
	pushl $34
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_35
_isr_wrapper_35:
	pushal
	pushl $35
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_36
_isr_wrapper_36:
	pushal
	pushl $36
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_37
_isr_wrapper_37:
	pushal
	pushl $37
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_38
_isr_wrapper_38:
	pushal
	pushl $38
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_39
_isr_wrapper_39:
	pushal
	pushl $39
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_40
_isr_wrapper_40:
	pushal
	pushl $40
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_41
_isr_wrapper_41:
	pushal
	pushl $41
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_42
_isr_wrapper_42:
	pushal
	pushl $42
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_43
_isr_wrapper_43:
	pushal
	pushl $43
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_44
_isr_wrapper_44:
	pushal
	pushl $44
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_45
_isr_wrapper_45:
	pushal
	pushl $45
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_46
_isr_wrapper_46:
	pushal
	pushl $46
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_47
_isr_wrapper_47:
	pushal
	pushl $47
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_48
_isr_wrapper_48:
	pushal
	pushl $48
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_49
_isr_wrapper_49:
	pushal
	pushl $49
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_50
_isr_wrapper_50:
	pushal
	pushl $50
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_51
_isr_wrapper_51:
	pushal
	pushl $51
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_52
_isr_wrapper_52:
	pushal
	pushl $52
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_53
_isr_wrapper_53:
	pushal
	pushl $53
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_54
_isr_wrapper_54:
	pushal
	pushl $54
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_55
_isr_wrapper_55:
	pushal
	pushl $55
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_56
_isr_wrapper_56:
	pushal
	pushl $56
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_57
_isr_wrapper_57:
	pushal
	pushl $57
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_58
_isr_wrapper_58:
	pushal
	pushl $58
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_59
_isr_wrapper_59:
	pushal
	pushl $59
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_60
_isr_wrapper_60:
	pushal
	pushl $60
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_61
_isr_wrapper_61:
	pushal
	pushl $61
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_62
_isr_wrapper_62:
	pushal
	pushl $62
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_63
_isr_wrapper_63:
	pushal
	pushl $63
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_64
_isr_wrapper_64:
	pushal
	pushl $64
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_65
_isr_wrapper_65:
	pushal
	pushl $65
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_66
_isr_wrapper_66:
	pushal
	pushl $66
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_67
_isr_wrapper_67:
	pushal
	pushl $67
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_68
_isr_wrapper_68:
	pushal
	pushl $68
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_69
_isr_wrapper_69:
	pushal
	pushl $69
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_70
_isr_wrapper_70:
	pushal
	pushl $70
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_71
_isr_wrapper_71:
	pushal
	pushl $71
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_72
_isr_wrapper_72:
	pushal
	pushl $72
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_73
_isr_wrapper_73:
	pushal
	pushl $73
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_74
_isr_wrapper_74:
	pushal
	pushl $74
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_75
_isr_wrapper_75:
	pushal
	pushl $75
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_76
_isr_wrapper_76:
	pushal
	pushl $76
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_77
_isr_wrapper_77:
	pushal
	pushl $77
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_78
_isr_wrapper_78:
	pushal
	pushl $78
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_79
_isr_wrapper_79:
	pushal
	pushl $79
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_80
_isr_wrapper_80:
	pushal
	pushl $80
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_81
_isr_wrapper_81:
	pushal
	pushl $81
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_82
_isr_wrapper_82:
	pushal
	pushl $82
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_83
_isr_wrapper_83:
	pushal
	pushl $83
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_84
_isr_wrapper_84:
	pushal
	pushl $84
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_85
_isr_wrapper_85:
	pushal
	pushl $85
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_86
_isr_wrapper_86:
	pushal
	pushl $86
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_87
_isr_wrapper_87:
	pushal
	pushl $87
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_88
_isr_wrapper_88:
	pushal
	pushl $88
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_89
_isr_wrapper_89:
	pushal
	pushl $89
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_90
_isr_wrapper_90:
	pushal
	pushl $90
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_91
_isr_wrapper_91:
	pushal
	pushl $91
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_92
_isr_wrapper_92:
	pushal
	pushl $92
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_93
_isr_wrapper_93:
	pushal
	pushl $93
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_94
_isr_wrapper_94:
	pushal
	pushl $94
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_95
_isr_wrapper_95:
	pushal
	pushl $95
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_96
_isr_wrapper_96:
	pushal
	pushl $96
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_97
_isr_wrapper_97:
	pushal
	pushl $97
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_98
_isr_wrapper_98:
	pushal
	pushl $98
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_99
_isr_wrapper_99:
	pushal
	pushl $99
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_100
_isr_wrapper_100:
	pushal
	pushl $100
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_101
_isr_wrapper_101:
	pushal
	pushl $101
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_102
_isr_wrapper_102:
	pushal
	pushl $102
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_103
_isr_wrapper_103:
	pushal
	pushl $103
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_104
_isr_wrapper_104:
	pushal
	pushl $104
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_105
_isr_wrapper_105:
	pushal
	pushl $105
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_106
_isr_wrapper_106:
	pushal
	pushl $106
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_107
_isr_wrapper_107:
	pushal
	pushl $107
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_108
_isr_wrapper_108:
	pushal
	pushl $108
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_109
_isr_wrapper_109:
	pushal
	pushl $109
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_110
_isr_wrapper_110:
	pushal
	pushl $110
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_111
_isr_wrapper_111:
	pushal
	pushl $111
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_112
_isr_wrapper_112:
	pushal
	pushl $112
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_113
_isr_wrapper_113:
	pushal
	pushl $113
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_114
_isr_wrapper_114:
	pushal
	pushl $114
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_115
_isr_wrapper_115:
	pushal
	pushl $115
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_116
_isr_wrapper_116:
	pushal
	pushl $116
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_117
_isr_wrapper_117:
	pushal
	pushl $117
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_118
_isr_wrapper_118:
	pushal
	pushl $118
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_119
_isr_wrapper_119:
	pushal
	pushl $119
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_120
_isr_wrapper_120:
	pushal
	pushl $120
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_121
_isr_wrapper_121:
	pushal
	pushl $121
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_122
_isr_wrapper_122:
	pushal
	pushl $122
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_123
_isr_wrapper_123:
	pushal
	pushl $123
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_124
_isr_wrapper_124:
	pushal
	pushl $124
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_125
_isr_wrapper_125:
	pushal
	pushl $125
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_126
_isr_wrapper_126:
	pushal
	pushl $126
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_127
_isr_wrapper_127:
	pushal
	pushl $127
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_128
_isr_wrapper_128:
	pushal
	pushl $128
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_129
_isr_wrapper_129:
	pushal
	pushl $129
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_130
_isr_wrapper_130:
	pushal
	pushl $130
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_131
_isr_wrapper_131:
	pushal
	pushl $131
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_132
_isr_wrapper_132:
	pushal
	pushl $132
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_133
_isr_wrapper_133:
	pushal
	pushl $133
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_134
_isr_wrapper_134:
	pushal
	pushl $134
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_135
_isr_wrapper_135:
	pushal
	pushl $135
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_136
_isr_wrapper_136:
	pushal
	pushl $136
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_137
_isr_wrapper_137:
	pushal
	pushl $137
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_138
_isr_wrapper_138:
	pushal
	pushl $138
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_139
_isr_wrapper_139:
	pushal
	pushl $139
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_140
_isr_wrapper_140:
	pushal
	pushl $140
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_141
_isr_wrapper_141:
	pushal
	pushl $141
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_142
_isr_wrapper_142:
	pushal
	pushl $142
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_143
_isr_wrapper_143:
	pushal
	pushl $143
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_144
_isr_wrapper_144:
	pushal
	pushl $144
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_145
_isr_wrapper_145:
	pushal
	pushl $145
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_146
_isr_wrapper_146:
	pushal
	pushl $146
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_147
_isr_wrapper_147:
	pushal
	pushl $147
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_148
_isr_wrapper_148:
	pushal
	pushl $148
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_149
_isr_wrapper_149:
	pushal
	pushl $149
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_150
_isr_wrapper_150:
	pushal
	pushl $150
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_151
_isr_wrapper_151:
	pushal
	pushl $151
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_152
_isr_wrapper_152:
	pushal
	pushl $152
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_153
_isr_wrapper_153:
	pushal
	pushl $153
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_154
_isr_wrapper_154:
	pushal
	pushl $154
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_155
_isr_wrapper_155:
	pushal
	pushl $155
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_156
_isr_wrapper_156:
	pushal
	pushl $156
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_157
_isr_wrapper_157:
	pushal
	pushl $157
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_158
_isr_wrapper_158:
	pushal
	pushl $158
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_159
_isr_wrapper_159:
	pushal
	pushl $159
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_160
_isr_wrapper_160:
	pushal
	pushl $160
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_161
_isr_wrapper_161:
	pushal
	pushl $161
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_162
_isr_wrapper_162:
	pushal
	pushl $162
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_163
_isr_wrapper_163:
	pushal
	pushl $163
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_164
_isr_wrapper_164:
	pushal
	pushl $164
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_165
_isr_wrapper_165:
	pushal
	pushl $165
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_166
_isr_wrapper_166:
	pushal
	pushl $166
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_167
_isr_wrapper_167:
	pushal
	pushl $167
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_168
_isr_wrapper_168:
	pushal
	pushl $168
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_169
_isr_wrapper_169:
	pushal
	pushl $169
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_170
_isr_wrapper_170:
	pushal
	pushl $170
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_171
_isr_wrapper_171:
	pushal
	pushl $171
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_172
_isr_wrapper_172:
	pushal
	pushl $172
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_173
_isr_wrapper_173:
	pushal
	pushl $173
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_174
_isr_wrapper_174:
	pushal
	pushl $174
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_175
_isr_wrapper_175:
	pushal
	pushl $175
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_176
_isr_wrapper_176:
	pushal
	pushl $176
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_177
_isr_wrapper_177:
	pushal
	pushl $177
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_178
_isr_wrapper_178:
	pushal
	pushl $178
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_179
_isr_wrapper_179:
	pushal
	pushl $179
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_180
_isr_wrapper_180:
	pushal
	pushl $180
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_181
_isr_wrapper_181:
	pushal
	pushl $181
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_182
_isr_wrapper_182:
	pushal
	pushl $182
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_183
_isr_wrapper_183:
	pushal
	pushl $183
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_184
_isr_wrapper_184:
	pushal
	pushl $184
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_185
_isr_wrapper_185:
	pushal
	pushl $185
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_186
_isr_wrapper_186:
	pushal
	pushl $186
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_187
_isr_wrapper_187:
	pushal
	pushl $187
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_188
_isr_wrapper_188:
	pushal
	pushl $188
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_189
_isr_wrapper_189:
	pushal
	pushl $189
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_190
_isr_wrapper_190:
	pushal
	pushl $190
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_191
_isr_wrapper_191:
	pushal
	pushl $191
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_192
_isr_wrapper_192:
	pushal
	pushl $192
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_193
_isr_wrapper_193:
	pushal
	pushl $193
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_194
_isr_wrapper_194:
	pushal
	pushl $194
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_195
_isr_wrapper_195:
	pushal
	pushl $195
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_196
_isr_wrapper_196:
	pushal
	pushl $196
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_197
_isr_wrapper_197:
	pushal
	pushl $197
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_198
_isr_wrapper_198:
	pushal
	pushl $198
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_199
_isr_wrapper_199:
	pushal
	pushl $199
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_200
_isr_wrapper_200:
	pushal
	pushl $200
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_201
_isr_wrapper_201:
	pushal
	pushl $201
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_202
_isr_wrapper_202:
	pushal
	pushl $202
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_203
_isr_wrapper_203:
	pushal
	pushl $203
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_204
_isr_wrapper_204:
	pushal
	pushl $204
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_205
_isr_wrapper_205:
	pushal
	pushl $205
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_206
_isr_wrapper_206:
	pushal
	pushl $206
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_207
_isr_wrapper_207:
	pushal
	pushl $207
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_208
_isr_wrapper_208:
	pushal
	pushl $208
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_209
_isr_wrapper_209:
	pushal
	pushl $209
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_210
_isr_wrapper_210:
	pushal
	pushl $210
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_211
_isr_wrapper_211:
	pushal
	pushl $211
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_212
_isr_wrapper_212:
	pushal
	pushl $212
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_213
_isr_wrapper_213:
	pushal
	pushl $213
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_214
_isr_wrapper_214:
	pushal
	pushl $214
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_215
_isr_wrapper_215:
	pushal
	pushl $215
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_216
_isr_wrapper_216:
	pushal
	pushl $216
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_217
_isr_wrapper_217:
	pushal
	pushl $217
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_218
_isr_wrapper_218:
	pushal
	pushl $218
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_219
_isr_wrapper_219:
	pushal
	pushl $219
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_220
_isr_wrapper_220:
	pushal
	pushl $220
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_221
_isr_wrapper_221:
	pushal
	pushl $221
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_222
_isr_wrapper_222:
	pushal
	pushl $222
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_223
_isr_wrapper_223:
	pushal
	pushl $223
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_224
_isr_wrapper_224:
	pushal
	pushl $224
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_225
_isr_wrapper_225:
	pushal
	pushl $225
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_226
_isr_wrapper_226:
	pushal
	pushl $226
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_227
_isr_wrapper_227:
	pushal
	pushl $227
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_228
_isr_wrapper_228:
	pushal
	pushl $228
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_229
_isr_wrapper_229:
	pushal
	pushl $229
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_230
_isr_wrapper_230:
	pushal
	pushl $230
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_231
_isr_wrapper_231:
	pushal
	pushl $231
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_232
_isr_wrapper_232:
	pushal
	pushl $232
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_233
_isr_wrapper_233:
	pushal
	pushl $233
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_234
_isr_wrapper_234:
	pushal
	pushl $234
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_235
_isr_wrapper_235:
	pushal
	pushl $235
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_236
_isr_wrapper_236:
	pushal
	pushl $236
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_237
_isr_wrapper_237:
	pushal
	pushl $237
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_238
_isr_wrapper_238:
	pushal
	pushl $238
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_239
_isr_wrapper_239:
	pushal
	pushl $239
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_240
_isr_wrapper_240:
	pushal
	pushl $240
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_241
_isr_wrapper_241:
	pushal
	pushl $241
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_242
_isr_wrapper_242:
	pushal
	pushl $242
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_243
_isr_wrapper_243:
	pushal
	pushl $243
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_244
_isr_wrapper_244:
	pushal
	pushl $244
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_245
_isr_wrapper_245:
	pushal
	pushl $245
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_246
_isr_wrapper_246:
	pushal
	pushl $246
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_247
_isr_wrapper_247:
	pushal
	pushl $247
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_248
_isr_wrapper_248:
	pushal
	pushl $248
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_249
_isr_wrapper_249:
	pushal
	pushl $249
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_250
_isr_wrapper_250:
	pushal
	pushl $250
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_251
_isr_wrapper_251:
	pushal
	pushl $251
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_252
_isr_wrapper_252:
	pushal
	pushl $252
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_253
_isr_wrapper_253:
	pushal
	pushl $253
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_254
_isr_wrapper_254:
	pushal
	pushl $254
	call   interrupts_handler
	popl %eax
	popal
	iret


.globl _isr_wrapper_255
_isr_wrapper_255:
	pushal
	pushl $255
	call   interrupts_handler
	popl %eax
	popal
	iret


